{"trial_id": "06", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.001, "conditions": [], "values": [0.001, 0.0001], "ordered": true}}, {"class_name": "Choice", "config": {"name": "optimizer", "default": "adam", "conditions": [], "values": ["adam", "sgd", "rmsprop"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "metrics", "default": "accuracy", "conditions": [], "values": ["accuracy", "precision"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "epochs", "default": 10, "conditions": [], "values": [10, 15], "ordered": true}}], "values": {"learning_rate": 0.001, "optimizer": "sgd", "metrics": "precision", "epochs": 10}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/jorge.vazquez.perez/miniconda3/envs/ccam/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/jorge.vazquez.perez/miniconda3/envs/ccam/lib/python3.11/site-packages/keras_tuner/src/engine/base_tuner.py\", line 238, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/jorge.vazquez.perez/miniconda3/envs/ccam/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/jorge.vazquez.perez/miniconda3/envs/ccam/lib/python3.11/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/tmp/ipykernel_122539/4154555428.py\", line 33, in fit\n    return model.fit(\n           ^^^^^^^^^^\n  File \"/home/jorge.vazquez.perez/miniconda3/envs/ccam/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/tmp/__autograph_generated_filehdpx5dna.py\", line 18, in tf__train_function\n    raise\nTypeError: in user code:\n\n    File \"/home/jorge.vazquez.perez/miniconda3/envs/ccam/lib/python3.11/site-packages/keras/src/engine/training.py\", line 1338, in train_function  *\n        return step_function(self, iterator)\n    File \"/home/jorge.vazquez.perez/miniconda3/envs/ccam/lib/python3.11/site-packages/keras/src/engine/training.py\", line 1322, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/home/jorge.vazquez.perez/miniconda3/envs/ccam/lib/python3.11/site-packages/keras/src/engine/training.py\", line 1303, in run_step  **\n        outputs = model.train_step(data)\n    File \"/home/jorge.vazquez.perez/miniconda3/envs/ccam/lib/python3.11/site-packages/keras/src/engine/training.py\", line 1085, in train_step\n        return self.compute_metrics(x, y, y_pred, sample_weight)\n    File \"/home/jorge.vazquez.perez/miniconda3/envs/ccam/lib/python3.11/site-packages/keras/src/engine/training.py\", line 1179, in compute_metrics\n        self.compiled_metrics.update_state(y, y_pred, sample_weight)\n    File \"/home/jorge.vazquez.perez/miniconda3/envs/ccam/lib/python3.11/site-packages/keras/src/engine/compile_utils.py\", line 605, in update_state\n        metric_obj.update_state(y_t, y_p, sample_weight=mask)\n    File \"/home/jorge.vazquez.perez/miniconda3/envs/ccam/lib/python3.11/site-packages/keras/src/utils/metrics_utils.py\", line 77, in decorated\n        update_op = update_state_fn(*args, **kwargs)\n    File \"/home/jorge.vazquez.perez/miniconda3/envs/ccam/lib/python3.11/site-packages/keras/src/metrics/base_metric.py\", line 140, in update_state_fn\n        return ag_update_state(*args, **kwargs)\n    File \"/home/jorge.vazquez.perez/miniconda3/envs/ccam/lib/python3.11/site-packages/keras/src/metrics/base_metric.py\", line 723, in update_state  **\n        matches = ag_fn(y_true, y_pred, **self._fn_kwargs)\n\n    TypeError: 'str' object is not callable\n\n"}